[package]
name = "yew-web3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18.0"
wasm-bindgen = {version = "0.2.67", features = ["serde-serialize"]}
js-sys = "0.3.44"
